name: MLOps CI (Potter)

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (Potter)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (Potter)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training (Potter)
        run: |
          python src/train.py

      - name: Run tests (Potter)
        run: |
          pytest
